### ISSUE TITLE
feat: create useMediaQuery, useSecTimer in react

### ISSUE THREAD

**Issue by Hanna922** [yourssu/Yrano#16]
# ISSUE ✅ : create useMediaQuery, useSecTimer in react

## 📖 Summary

- useMediaQuery (값 몇 개 고정 vs 완전 자유롭게)
- useSecTimer (현재 soomsil에서 useSecondTimer)

## ✅ TODO

- [x] create useSecTimer (with docs, test code)
- [x] create useMediaQuery (with docs, test code)
- [x] modify useInterval docs
